spring.application.name=jgames-sever

spring.datasource.url=jdbc:postgresql://ep-nameless-band-aqdn6fvy-pooler.c-8.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6F3KyQvLdTzf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
